### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#7]
- [x] Be able to bulk delete items in the admin
- [x] Be able to bulk modify items in the admin
- [x] Improve pagination when dealing with lots of data in a table.
- [x] CSV export
- [x] Add a custom widget for Interval fields - currently just accepts a number of seconds.
- [x] Use FastAPI for the API
- [x] User management - creating users and changing passwords via the UI
- [x] Be able to change the page size (i.e. number of results per page) dynamically in the UI
- [x] Be able to specify a site name in `create_admin`, so the UI shows `MySite Admin` in the nav bar, rather than the default `Piccolo Admin`

**Comment by sinisaos** [comment]
Hi Daniel
In roadmap CSV export isn't applied yet. I made export to csv with help of https://www.npmjs.com/package/vue-json-excel. I tried on 10000 records with filtering and sorting and work fine. I can make PR that you can see code and try it. 

![admin](https://user-images.githubusercontent.com/30960668/102751851-e0140400-4368-11eb-9843-3a7909c175ad.png)

What do you think?

**Comment by dantownsend** [comment]
@sinisaos Yes, that would be great. I assumed it would require some backend work for CSV exporting to work, but if there's a JS library for it, even better!

**Comment by sinisaos** [comment]
This was all resolved a long time ago.
